# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainVOne.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1058, 769)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CURRENT_DATE = QtWidgets.QLabel(self.centralwidget)
        self.CURRENT_DATE.setGeometry(QtCore.QRect(440, 40, 201, 51))
        self.CURRENT_DATE.setObjectName("CURRENT_DATE")
        self.TEXT_INPUT = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.TEXT_INPUT.setGeometry(QtCore.QRect(290, 100, 451, 191))
        self.TEXT_INPUT.setObjectName("TEXT_INPUT")
        self.SUBMIT = QtWidgets.QPushButton(self.centralwidget)
        self.SUBMIT.setGeometry(QtCore.QRect(450, 640, 141, 41))
        self.SUBMIT.setObjectName("SUBMIT")
        self.PAST_ENTRY = QtWidgets.QPushButton(self.centralwidget)
        self.PAST_ENTRY.setGeometry(QtCore.QRect(60, 560, 151, 101))
        self.PAST_ENTRY.setObjectName("PAST_ENTRY")
        self.DRAW_INPUT = QtWidgets.QLabel(self.centralwidget)
        self.DRAW_INPUT.setGeometry(QtCore.QRect(290, 310, 451, 311))
        self.DRAW_INPUT.setObjectName("DRAW_INPUT")
        self.AVATAR = QtWidgets.QLabel(self.centralwidget)
        self.AVATAR.setGeometry(QtCore.QRect(760, 140, 250, 500))
        self.AVATAR.setObjectName("AVATAR")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 10, 171, 221))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.STREAK = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.STREAK.setFont(font)
        self.STREAK.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.STREAK.setObjectName("STREAK")
        self.verticalLayout.addWidget(self.STREAK)
        self.POINTS = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.POINTS.setFont(font)
        self.POINTS.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.POINTS.setObjectName("POINTS")
        self.verticalLayout.addWidget(self.POINTS)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1058, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CURRENT_DATE.setText(_translate("MainWindow", "TextLabel"))
        self.SUBMIT.setText(_translate("MainWindow", "PushButton"))
        self.PAST_ENTRY.setText(_translate("MainWindow", "PushButton"))
        self.DRAW_INPUT.setText(_translate("MainWindow", "TextLabel"))
        self.AVATAR.setText(_translate("MainWindow", "TextLabel"))
        self.STREAK.setText(_translate("MainWindow", "Streak"))
        self.POINTS.setText(_translate("MainWindow", "Points:"))
