# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splashTwo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 60, 271, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LOADING = QtWidgets.QLabel(self.layoutWidget)
        self.LOADING.setObjectName("LOADING")
        self.verticalLayout.addWidget(self.LOADING)
        self.PROGRESS = QtWidgets.QProgressBar(self.layoutWidget)
        self.PROGRESS.setStyleSheet("QProgressBar::chunk{\n"
"    background-color:#FA8072;\n"
"}")
        self.PROGRESS.setProperty("value", 24)
        self.PROGRESS.setObjectName("PROGRESS")
        self.verticalLayout.addWidget(self.PROGRESS)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.LOADING.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; color:#0aad84;\">LOADING</span></p></body></html>"))
