# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wuh.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Confirm = QtWidgets.QPushButton(self.centralwidget)
        self.Confirm.setGeometry(QtCore.QRect(190, 330, 281, 81))
        self.Confirm.setObjectName("Confirm")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(190, 100, 281, 211))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.Slut = QtWidgets.QCheckBox(self.splitter)
        self.Slut.setObjectName("Slut")
        self.Bitch = QtWidgets.QCheckBox(self.splitter)
        self.Bitch.setObjectName("Bitch")
        self.Whore = QtWidgets.QCheckBox(self.splitter)
        self.Whore.setObjectName("Whore")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Confirm.setText(_translate("MainWindow", "Confirm"))
        self.Slut.setText(_translate("MainWindow", "Slut"))
        self.Bitch.setText(_translate("MainWindow", "Bitch"))
        self.Whore.setText(_translate("MainWindow", "Whore"))
